### PR TITLE
chore(deploy): new function

### PR DESCRIPTION
**Pull request by muhx**

### CODE REVIEW

**Comment by mileops** [comment]
Ran Plan for project: `temperature-converter` dir: `infra` workspace: `default`

<details><summary>Show Output</summary>

```diff
data.archive_file.default: Reading...
data.archive_file.default: Read complete after 0s [id=3a589eaa9cf050871d661a2f85fa4ea632cd483f]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # google_cloud_run_service_iam_member.member will be created
+ resource "google_cloud_run_service_iam_member" "member" {
+       etag     = (known after apply)
+       id       = (known after apply)
+       location = "us-central1"
+       member   = "allAuthenticatedUsers"
+       project  = (known after apply)
+       role     = "roles/run.invoker"
+       service  = "temperature-converter"
    }

  # google_cloudfunctions2_function.default will be created
+ resource "google_cloudfunctions2_function" "default" {
+       description      = "Function to convert temperature"
+       effective_labels = (known after apply)
+       environment      = (known after apply)
+       id               = (known after apply)
+       location         = "us-central1"
+       name             = "temperature-converter"
+       project          = "id-rd-ai-demo"
+       state            = (known after apply)
+       terraform_labels = (known after apply)
+       update_time      = (known after apply)
+       url              = (known after apply)

+       build_config {
+           build                 = (known after apply)
+           entry_point           = "convertTemp"
+           environment_variables = (known after apply)
+           runtime               = "nodejs20"

+           source {
+               storage_source {
+                   bucket     = (known after apply)
+                   generation = (known after apply)
+                   object     = "function-source.zip"
                }
            }
        }

+       service_config {
+           all_traffic_on_latest_revision   = true
+           available_cpu                    = (known after apply)
+           available_memory                 = "256M"
+           gcf_uri                          = (known after apply)
+           ingress_settings                 = "ALLOW_ALL"
+           max_instance_count               = 1
+           max_instance_request_concurrency = (known after apply)
+           service                          = (known after apply)
+           service_account_email            = (known after apply)
+           timeout_seconds                  = 60
+           uri                              = (known after apply)
        }
    }

  # google_secret_manager_secret.secret_name will be created
+ resource "google_secret_manager_secret" "secret_name" {
+       create_time           = (known after apply)
+       effective_annotations = (known after apply)
+       effective_labels      = (known after apply)
+       expire_time           = (known after apply)
+       id                    = (known after apply)
+       name                  = (known after apply)
+       project               = "id-rd-ai-demo"
+       secret_id             = "secret"
+       terraform_labels      = (known after apply)

+       replication {
+           user_managed {
+               replicas {
+                   location = "us-central1"
                }
            }
        }
    }

  # google_storage_bucket.default will be created
+ resource "google_storage_bucket" "default" {
+       effective_labels            = (known after apply)
+       force_destroy               = false
+       id                          = (known after apply)
+       location                    = "US"
+       name                        = (known after apply)
+       project                     = (known after apply)
+       public_access_prevention    = (known after apply)
+       self_link                   = (known after apply)
+       storage_class               = "STANDARD"
+       terraform_labels            = (known after apply)
+       uniform_bucket_level_access = true
+       url                         = (known after apply)

+       versioning (known after apply)

+       website (known after apply)
    }

  # google_storage_bucket_object.object will be created
+ resource "google_storage_bucket_object" "object" {
+       bucket         = (known after apply)
+       content        = (sensitive value)
+       content_type   = (known after apply)
+       crc32c         = (known after apply)
+       detect_md5hash = "different hash"
+       id             = (known after apply)
+       kms_key_name   = (known after apply)
+       md5hash        = (known after apply)
+       media_link     = (known after apply)
+       name           = "function-source.zip"
+       output_name    = (known after apply)
+       self_link      = (known after apply)
+       source         = "/tmp/temperature-converter.zip"
+       storage_class  = (known after apply)
    }

  # random_id.default will be created
+ resource "random_id" "default" {
+       b64_std     = (known after apply)
+       b64_url     = (known after apply)
+       byte_length = 8
+       dec         = (known after apply)
+       hex         = (known after apply)
+       id          = (known after apply)
    }

Plan: 6 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ function_uri = (known after apply)
```
</details>

* :arrow_forward: To **apply** this plan, comment:
  ```shell
  atlantis apply -p temperature-converter
  ```
* :put_litter_in_its_place: To **delete** this plan and lock, click [here](https://atlantis.mile.codes/lock?id=cloudmileid%252Ftemperature-converter%252Finfra%252Fdefault)
* :repeat: To **plan** this project again, comment:
  ```shell
  atlantis plan -p temperature-converter
  ```
Plan: 6 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this Pull Request, comment:
  ```shell
  atlantis apply
  ```
* :put_litter_in_its_place: To **delete** all plans and locks from this Pull Request, comment:
  ```shell
  atlantis unlock
  ```

**Comment by muhx** [comment]
atlantis apply

**Comment by mileops** [comment]
Ran Apply for project: `temperature-converter` dir: `infra` workspace: `default`

<details><summary>Show Output</summary>

```diff
random_id.default: Creating...
random_id.default: Creation complete after 0s [id=bBE1022ehiY]
google_storage_bucket.default: Creating...
google_secret_manager_secret.secret_name: Creating...
google_secret_manager_secret.secret_name: Creation complete after 0s [id=projects/id-rd-ai-demo/secrets/secret]
google_storage_bucket.default: Creation complete after 1s [id=6c1135d36d9e8626-gcf-source]
google_storage_bucket_object.object: Creating...
google_storage_bucket_object.object: Creation complete after 0s [id=6c1135d36d9e8626-gcf-source-function-source.zip]
google_cloudfunctions2_function.default: Creating...
google_cloudfunctions2_function.default: Still creating... [10s elapsed]
google_cloudfunctions2_function.default: Still creating... [20s elapsed]
google_cloudfunctions2_function.default: Still creating... [30s elapsed]
google_cloudfunctions2_function.default: Still creating... [40s elapsed]
google_cloudfunctions2_function.default: Still creating... [50s elapsed]
google_cloudfunctions2_function.default: Still creating... [1m0s elapsed]
google_cloudfunctions2_function.default: Creation complete after 1m1s [id=projects/id-rd-ai-demo/locations/us-central1/functions/temperature-converter]
google_cloud_run_service_iam_member.member: Creating...
google_cloud_run_service_iam_member.member: Creation complete after 4s [id=v1/projects/id-rd-ai-demo/locations/us-central1/services/temperature-converter/roles/run.invoker/allAuthenticatedUsers]

Apply complete! Resources: 6 added, 0 changed, 0 destroyed.

Outputs:

function_uri = "https://temperature-converter-xxh53ud4oq-uc.a.run.app"
```

</details>

**Comment by mileops** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by mileops** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `infra` workspace: `default`

**Pull request merged**
