### PR TITLE
chore(destroy): destroy function

### PR DESCRIPTION
**Pull request by muhx**

### CODE REVIEW

**Comment by mileops** [comment]
Ran Plan for project: `temperature-converter` dir: `infra` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
! update in-place

Terraform will perform the following actions:

  # google_cloudfunctions2_function.default will be updated in-place
! resource "google_cloudfunctions2_function" "default" {
        id               = "projects/id-rd-ai-demo/locations/us-central1/functions/temperature-converter"
        name             = "temperature-converter"
        # (11 unchanged attributes hidden)

!       build_config {
-           docker_repository     = "projects/id-rd-ai-demo/locations/us-central1/repositories/gcf-artifacts" -> null
            # (5 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

!       service_config {
!           environment_variables            = {
-               "LOG_EXECUTION_ID" = "true" -> null
            }
            # (14 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
</details>

* :arrow_forward: To **apply** this plan, comment:
  ```shell
  atlantis apply -p temperature-converter
  ```
* :put_litter_in_its_place: To **delete** this plan and lock, click [here](https://atlantis.mile.codes/lock?id=cloudmileid%252Ftemperature-converter%252Finfra%252Fdefault)
* :repeat: To **plan** this project again, comment:
  ```shell
  atlantis plan -p temperature-converter
  ```
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this Pull Request, comment:
  ```shell
  atlantis apply
  ```
* :put_litter_in_its_place: To **delete** all plans and locks from this Pull Request, comment:
  ```shell
  atlantis unlock
  ```

**Comment by muhx** [comment]
atlantis plan -- -destroy

**Comment by mileops** [comment]
Ran Plan for project: `temperature-converter` dir: `infra` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # google_cloud_run_service_iam_member.member will be destroyed
- resource "google_cloud_run_service_iam_member" "member" {
-       etag     = "BwYolRIh2DU=" -> null
-       id       = "v1/projects/id-rd-ai-demo/locations/us-central1/services/temperature-converter/roles/run.invoker/allAuthenticatedUsers" -> null
-       location = "us-central1" -> null
-       member   = "allAuthenticatedUsers" -> null
-       project  = "id-rd-ai-demo" -> null
-       role     = "roles/run.invoker" -> null
-       service  = "v1/projects/id-rd-ai-demo/locations/us-central1/services/temperature-converter" -> null
    }

  # google_cloudfunctions2_function.default will be destroyed
- resource "google_cloudfunctions2_function" "default" {
-       description      = "Function to convert temperature" -> null
-       effective_labels = {} -> null
-       environment      = "GEN_2" -> null
-       id               = "projects/id-rd-ai-demo/locations/us-central1/functions/temperature-converter" -> null
-       labels           = {} -> null
-       location         = "us-central1" -> null
-       name             = "temperature-converter" -> null
-       project          = "id-rd-ai-demo" -> null
-       state            = "ACTIVE" -> null
-       terraform_labels = {} -> null
-       update_time      = "2024-12-06T07:36:18.153822490Z" -> null
-       url              = "https://us-central1-id-rd-ai-demo.cloudfunctions.net/temperature-converter" -> null
        # (1 unchanged attribute hidden)

-       build_config {
-           build                 = "projects/1098550132960/locations/us-central1/builds/c1150c23-3ad0-4fe6-bee8-75ea8d71932f" -> null
-           docker_repository     = "projects/id-rd-ai-demo/locations/us-central1/repositories/gcf-artifacts" -> null
-           entry_point           = "convertTemp" -> null
-           environment_variables = {} -> null
-           runtime               = "nodejs20" -> null
            # (1 unchanged attribute hidden)

-           source {
-               storage_source {
-                   bucket     = "6c1135d36d9e8626-gcf-source" -> null
-                   generation = 1733470518562461 -> null
-                   object     = "function-source.zip" -> null
                }
            }
        }

-       service_config {
-           all_traffic_on_latest_revision   = true -> null
-           available_cpu                    = "0.1666" -> null
-           available_memory                 = "256M" -> null
-           environment_variables            = {
-               "LOG_EXECUTION_ID" = "true"
            } -> null
-           ingress_settings                 = "ALLOW_ALL" -> null
-           max_instance_count               = 1 -> null
-           max_instance_request_concurrency = 1 -> null
-           min_instance_count               = 0 -> null
-           service                          = "projects/id-rd-ai-demo/locations/us-central1/services/temperature-converter" -> null
-           service_account_email            = "1098550132960-compute@developer.gserviceaccount.com" -> null
-           timeout_seconds                  = 60 -> null
-           uri                              = "https://temperature-converter-xxh53ud4oq-uc.a.run.app" -> null
            # (3 unchanged attributes hidden)
        }
    }

  # google_secret_manager_secret.secret_name will be destroyed
- resource "google_secret_manager_secret" "secret_name" {
-       annotations           = {} -> null
-       create_time           = "2024-12-06T07:35:16.763544Z" -> null
-       effective_annotations = {} -> null
-       effective_labels      = {} -> null
-       id                    = "projects/id-rd-ai-demo/secrets/secret" -> null
-       labels                = {} -> null
-       name                  = "projects/1098550132960/secrets/secret" -> null
-       project               = "id-rd-ai-demo" -> null
-       secret_id             = "secret" -> null
-       terraform_labels      = {} -> null
-       version_aliases       = {} -> null
        # (1 unchanged attribute hidden)

-       replication {
-           user_managed {
-               replicas {
-                   location = "us-central1" -> null
                }
            }
        }
    }

  # google_storage_bucket.default will be destroyed
- resource "google_storage_bucket" "default" {
-       default_event_based_hold    = false -> null
-       effective_labels            = {} -> null
-       force_destroy               = false -> null
-       id                          = "6c1135d36d9e8626-gcf-source" -> null
-       labels                      = {} -> null
-       location                    = "US" -> null
-       name                        = "6c1135d36d9e8626-gcf-source" -> null
-       project                     = "id-rd-ai-demo" -> null
-       public_access_prevention    = "inherited" -> null
-       requester_pays              = false -> null
-       self_link                   = "https://www.googleapis.com/storage/v1/b/6c1135d36d9e8626-gcf-source" -> null
-       storage_class               = "STANDARD" -> null
-       terraform_labels            = {} -> null
-       uniform_bucket_level_access = true -> null
-       url                         = "gs://6c1135d36d9e8626-gcf-source" -> null
    }

  # google_storage_bucket_object.object will be destroyed
- resource "google_storage_bucket_object" "object" {
-       bucket              = "6c1135d36d9e8626-gcf-source" -> null
-       content_type        = "application/zip" -> null
-       crc32c              = "omhUxg==" -> null
-       detect_md5hash      = "3VitOIiBRC50DoGUn1xROg==" -> null
-       event_based_hold    = false -> null
-       id                  = "6c1135d36d9e8626-gcf-source-function-source.zip" -> null
-       md5hash             = "3VitOIiBRC50DoGUn1xROg==" -> null
-       media_link          = "https://storage.googleapis.com/download/storage/v1/b/6c1135d36d9e8626-gcf-source/o/function-source.zip?generation=1733470518014065&alt=media" -> null
-       metadata            = {} -> null
-       name                = "function-source.zip" -> null
-       output_name         = "function-source.zip" -> null
-       self_link           = "https://www.googleapis.com/storage/v1/b/6c1135d36d9e8626-gcf-source/o/function-source.zip" -> null
-       source              = "/tmp/temperature-converter.zip" -> null
-       storage_class       = "STANDARD" -> null
-       temporary_hold      = false -> null
        # (5 unchanged attributes hidden)
    }

  # random_id.default will be destroyed
- resource "random_id" "default" {
-       b64_std     = "bBE1022ehiY=" -> null
-       b64_url     = "bBE1022ehiY" -> null
-       byte_length = 8 -> null
-       dec         = "7787064412893775398" -> null
-       hex         = "6c1135d36d9e8626" -> null
-       id          = "bBE1022ehiY" -> null
    }

Plan: 0 to add, 0 to change, 6 to destroy.

Changes to Outputs:
- function_uri = "https://temperature-converter-xxh53ud4oq-uc.a.run.app" -> null
```
</details>

* :arrow_forward: To **apply** this plan, comment:
  ```shell
  atlantis apply -p temperature-converter
  ```
* :put_litter_in_its_place: To **delete** this plan and lock, click [here](https://atlantis.mile.codes/lock?id=cloudmileid%252Ftemperature-converter%252Finfra%252Fdefault)
* :repeat: To **plan** this project again, comment:
  ```shell
  atlantis plan -p temperature-converter -- -destroy
  ```
Plan: 0 to add, 0 to change, 6 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this Pull Request, comment:
  ```shell
  atlantis apply
  ```
* :put_litter_in_its_place: To **delete** all plans and locks from this Pull Request, comment:
  ```shell
  atlantis unlock
  ```

**Comment by muhx** [comment]
atlantis apply

**Comment by mileops** [comment]
Ran Apply for project: `temperature-converter` dir: `infra` workspace: `default`

<details><summary>Show Output</summary>

```diff
google_cloud_run_service_iam_member.member: Destroying... [id=v1/projects/id-rd-ai-demo/locations/us-central1/services/temperature-converter/roles/run.invoker/allAuthenticatedUsers]
google_secret_manager_secret.secret_name: Destroying... [id=projects/id-rd-ai-demo/secrets/secret]
google_secret_manager_secret.secret_name: Destruction complete after 0s
google_cloud_run_service_iam_member.member: Destruction complete after 4s
google_cloudfunctions2_function.default: Destroying... [id=projects/id-rd-ai-demo/locations/us-central1/functions/temperature-converter]
google_cloudfunctions2_function.default: Still destroying... [id=projects/id-rd-ai-demo/locations/us-central1/functions/temperature-converter, 10s elapsed]
google_cloudfunctions2_function.default: Destruction complete after 10s
google_storage_bucket_object.object: Destroying... [id=6c1135d36d9e8626-gcf-source-function-source.zip]
google_storage_bucket_object.object: Destruction complete after 0s
google_storage_bucket.default: Destroying... [id=6c1135d36d9e8626-gcf-source]
google_storage_bucket.default: Destruction complete after 0s
random_id.default: Destroying... [id=bBE1022ehiY]
random_id.default: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 6 destroyed.
```

</details>

**Comment by mileops** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by mileops** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `infra` workspace: `default`

**Pull request merged**
